# Generated by Django 5.1.1 on 2024-10-08 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_admin', models.CharField(max_length=250)),
                ('email_admin', models.CharField(max_length=200)),
                ('password_admin', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_groupe', models.CharField(max_length=250)),
                ('folowers', models.IntegerField(max_length=100)),
                ('pub', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_admin', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('name_groupe', models.CharField(max_length=250)),
                ('date_pub', models.DateTimeField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_admin', to='blog.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Postes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='Images/')),
                ('date_poste', models.DateTimeField(auto_now_add=True)),
                ('user_poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
